version: '3'

services:
  backend:
    build: ./
    container_name: quiz_container
    working_dir: /quizez
    command: ["./commands/start_server.sh"]
    ports:
      - 8010:8000
    volumes:
      - ./src:/quizez/src
      - ./commands:/quizez/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      restart: on-failure
      env_file:
        - .env
      ports:
        - 5055:80
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      depends_on:
        - postgres

  mongodb:
    image: mongo:3-stretch
    platform: linux/amd64
    container_name: mongo_db_container
    ports:
      - 27017:27017
    command: [ "--bind_ip_all", "--smallfiles" ]
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    restart: on-failure

  mongoadmin:
    image: mongo-express
    platform: linux/amd64
    container_name: mongo_admin_container
    ports:
      - 8091:8081
    env_file:
      - .env
    restart: on-failure
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
    mongo_data: { }
    pg_data: { }
    pgadmin_data: { }
